---
output: html_document
---

## فرع الاسكندرية
```{r echo=FALSE, fig.width=20, fig.align="center"}
library(data.tree)
#Elmongui <- Node$new("المنجى")
#dots1Elmongui <- Elmongui$AddChild(" ")
#dots2Elmongui <- Elmongui$AddChild("  ")
#dots3Elmongui <- Elmongui$AddChild("   ")

# ElsaeedElmongui
#ElsaeedElmongui <- dots2Elmongui$AddChild("السعيد")

# ElaissawyElmongui
#ElaissawyElmongui <- dots3Elmongui$AddChild("العيسوي")

# AhmedMohamedElmongui
AhmedMohamedElmongui <- Node$new("أحمد محمد المنجى")
MahmoudAhmedMohamedElmongui <-  AhmedMohamedElmongui$AddChild("محمود")
ElsayedAhmedMohamedElmongui <-  AhmedMohamedElmongui$AddChild("السيد")
MohamedAhmedMohamedElmongui <-  AhmedMohamedElmongui$AddChild("محمد")
HassanAhmedMohamedElmongui <-  AhmedMohamedElmongui$AddChild("حسن")
AlyAhmedMohamedElmongui <-  AhmedMohamedElmongui$AddChild("على")

# MahmoudAhmedMohamedElmongui
AlyMahmoudAhmedMohamedElmongui <-  MahmoudAhmedMohamedElmongui$AddChild("على")
MohamedAlyMahmoudAhmedMohamedElmongui <-  AlyMahmoudAhmedMohamedElmongui$AddChild("محمد")
AhmedMohamedAlyMahmoudAhmedMohamedElmongui <-  MohamedAlyMahmoudAhmedMohamedElmongui$AddChild("أحمد")
AlyMohamedAlyMahmoudAhmedMohamedElmongui <-  MohamedAlyMahmoudAhmedMohamedElmongui$AddChild("على")
NematMohamedAlyMahmoudAhmedMohamedElmongui <-  MohamedAlyMahmoudAhmedMohamedElmongui$AddChild("نعمة")
AhmedAlyMahmoudAhmedMohamedElmongui <-  AlyMahmoudAhmedMohamedElmongui$AddChild("أحمد")
AidaAhmedAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyMahmoudAhmedMohamedElmongui$AddChild("عايدة/منى")
MohamedAhmedAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyMahmoudAhmedMohamedElmongui$AddChild("محمد")
AhmedMohamedAhmedAlyMahmoudAhmedMohamedElmongui <-  MohamedAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("أحمد")
DinaMohamedAhmedAlyMahmoudAhmedMohamedElmongui <-  MohamedAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("دينا")
HossameldeenMohamedAhmedAlyMahmoudAhmedMohamedElmongui <-  MohamedAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("حسام الدين")
SamehAhmedAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyMahmoudAhmedMohamedElmongui$AddChild("سامح")
NourhanSamehAhmedAlyMahmoudAhmedMohamedElmongui <-  SamehAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("نورهان")
MariamAhmedAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyMahmoudAhmedMohamedElmongui$AddChild("مريم")
ArafatAhmedAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyMahmoudAhmedMohamedElmongui$AddChild("عرفات")
MennaArafatAhmedAlyMahmoudAhmedMohamedElmongui <-  ArafatAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("منةالله")
AhmedArafatAhmedAlyMahmoudAhmedMohamedElmongui <-  ArafatAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("أحمد")
OmarArafatAhmedAlyMahmoudAhmedMohamedElmongui <-  ArafatAhmedAlyMahmoudAhmedMohamedElmongui$AddChild("عمر")
MahmoudAlyMahmoudAhmedMohamedElmongui <-  AlyMahmoudAhmedMohamedElmongui$AddChild("محمود")
AlaaMahmoudAlyMahmoudAhmedMohamedElmongui <-  MahmoudAlyMahmoudAhmedMohamedElmongui$AddChild("علاء")
AzzaMahmoudAlyMahmoudAhmedMohamedElmongui <-  MahmoudAlyMahmoudAhmedMohamedElmongui$AddChild("عزة")
HananMahmoudAlyMahmoudAhmedMohamedElmongui <-  MahmoudAlyMahmoudAhmedMohamedElmongui$AddChild("حنان")
MohamedMahmoudAlyMahmoudAhmedMohamedElmongui <-  MahmoudAlyMahmoudAhmedMohamedElmongui$AddChild("محمد")
HoureyaAlyMahmoudAhmedMohamedElmongui <-  AlyMahmoudAhmedMohamedElmongui$AddChild("حورية")
AlyAlyMahmoudAhmedMohamedElmongui <-  AlyMahmoudAhmedMohamedElmongui$AddChild("على")
SherifAlyAlyMahmoudAhmedMohamedElmongui <-  AlyAlyMahmoudAhmedMohamedElmongui$AddChild("شريف")
MarwanSherifAlyAlyMahmoudAhmedMohamedElmongui <-  SherifAlyAlyMahmoudAhmedMohamedElmongui$AddChild("مروان")
MalakSherifAlyAlyMahmoudAhmedMohamedElmongui <-  SherifAlyAlyMahmoudAhmedMohamedElmongui$AddChild("ملك")
MonayaSherifAlyAlyMahmoudAhmedMohamedElmongui <-  SherifAlyAlyMahmoudAhmedMohamedElmongui$AddChild("منايا")
AhmedAlyAlyMahmoudAhmedMohamedElmongui <-  AlyAlyMahmoudAhmedMohamedElmongui$AddChild("أحمد")
EyadAhmedAlyAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyAlyMahmoudAhmedMohamedElmongui$AddChild("إياد")
ArwaAhmedAlyAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyAlyMahmoudAhmedMohamedElmongui$AddChild("أروى")
AnnAhmedAlyAlyMahmoudAhmedMohamedElmongui <-  AhmedAlyAlyMahmoudAhmedMohamedElmongui$AddChild("آن")
HanafyMahmoudAhmedMohamedElmongui <-  MahmoudAhmedMohamedElmongui$AddChild("حنفى")
ElberensMahmoudAhmedMohamedElmongui <-  MahmoudAhmedMohamedElmongui$AddChild("البرنس")
MohamedMahmoudAhmedMohamedElmongui <-  MahmoudAhmedMohamedElmongui$AddChild("محمد")
GalalMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("جلال")
NaglaaGalalMohamedMahmoudAhmedMohamedElmongui <-  GalalMohamedMahmoudAhmedMohamedElmongui$AddChild("نجلاء")
HichamGalalMohamedMahmoudAhmedMohamedElmongui <-  GalalMohamedMahmoudAhmedMohamedElmongui$AddChild("هشام")
YahyaHichamGalalMohamedMahmoudAhmedMohamedElmongui <-  HichamGalalMohamedMahmoudAhmedMohamedElmongui$AddChild("يحيى")
MuhammadHichamGalalMohamedMahmoudAhmedMohamedElmongui <-  HichamGalalMohamedMahmoudAhmedMohamedElmongui$AddChild("محمد")
LinaHichamGalalMohamedMahmoudAhmedMohamedElmongui <-  HichamGalalMohamedMahmoudAhmedMohamedElmongui$AddChild("لينة")
EhabGalalMohamedMahmoudAhmedMohamedElmongui <-  GalalMohamedMahmoudAhmedMohamedElmongui$AddChild("ايهاب")
MariamEhabGalalMohamedMahmoudAhmedMohamedElmongui <-  EhabGalalMohamedMahmoudAhmedMohamedElmongui$AddChild("مريم")
SaraEhabGalalMohamedMahmoudAhmedMohamedElmongui <-  EhabGalalMohamedMahmoudAhmedMohamedElmongui$AddChild("ساره")
YoussefMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("يوسف")
GihanYoussefMohamedMahmoudAhmedMohamedElmongui <-  YoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("جيهان")
AhmedYoussefMohamedMahmoudAhmedMohamedElmongui <-  YoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("أحمد")
JanaAhmedYoussefMohamedMahmoudAhmedMohamedElmongui <-  AhmedYoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("جنى")
FaridaAhmedYoussefMohamedMahmoudAhmedMohamedElmongui <-  AhmedYoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("فريدة")
AmanyYoussefMohamedMahmoudAhmedMohamedElmongui <-  YoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("أماني")
MostafaYoussefMohamedMahmoudAhmedMohamedElmongui <-  YoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("مصطفى")
OmarMostafaYoussefMohamedMahmoudAhmedMohamedElmongui <-  MostafaYoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("عمر")
AsmaaYoussefMohamedMahmoudAhmedMohamedElmongui <-  YoussefMohamedMahmoudAhmedMohamedElmongui$AddChild("أسماء")
EnsafMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("انصاف")
MRefeatMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("محمد رفعت")
EssamMRefeatMohamedMahmoudAhmedMohamedElmongui <-  MRefeatMohamedMahmoudAhmedMohamedElmongui$AddChild("عصام")
SallyMRefeatMohamedMahmoudAhmedMohamedElmongui <-  MRefeatMohamedMahmoudAhmedMohamedElmongui$AddChild("سالي")
SamiMRefeatMohamedMahmoudAhmedMohamedElmongui <-  MRefeatMohamedMahmoudAhmedMohamedElmongui$AddChild("سامي")
AHamdyMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("أحمد حمدي")
MohamedAHamdyMohamedMahmoudAhmedMohamedElmongui <-  AHamdyMohamedMahmoudAhmedMohamedElmongui$AddChild("محمد")
TaliaMohamedAHamdyMohamedMahmoudAhmedMohamedElmongui <-  MohamedAHamdyMohamedMahmoudAhmedMohamedElmongui$AddChild("تاليا")
MoatazAHamdyMohamedMahmoudAhmedMohamedElmongui <-  AHamdyMohamedMahmoudAhmedMohamedElmongui$AddChild("معتز")
SoheirMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("سهير")
HassanMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("حسن")
EmanHassanMohamedMahmoudAhmedMohamedElmongui <-  HassanMohamedMahmoudAhmedMohamedElmongui$AddChild("إيمان")
AhmedHassanMohamedMahmoudAhmedMohamedElmongui <-  HassanMohamedMahmoudAhmedMohamedElmongui$AddChild("أحمد")
AdamAhmedHassanMohamedMahmoudAhmedMohamedElmongui <-  AhmedHassanMohamedMahmoudAhmedMohamedElmongui$AddChild("آدم")
AmiraHassanMohamedMahmoudAhmedMohamedElmongui <-  HassanMohamedMahmoudAhmedMohamedElmongui$AddChild("أميرة")
RaniaHassanMohamedMahmoudAhmedMohamedElmongui <-  HassanMohamedMahmoudAhmedMohamedElmongui$AddChild("رانيا")
MahmoudMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("محمود")
MervatMahmoudMohamedMahmoudAhmedMohamedElmongui <-  MahmoudMohamedMahmoudAhmedMohamedElmongui$AddChild("مرفت")
DinaMahmoudMohamedMahmoudAhmedMohamedElmongui <-  MahmoudMohamedMahmoudAhmedMohamedElmongui$AddChild("دينا")
AsmaaMahmoudMohamedMahmoudAhmedMohamedElmongui <-  MahmoudMohamedMahmoudAhmedMohamedElmongui$AddChild("أسماء")
MostafaMahmoudMohamedMahmoudAhmedMohamedElmongui <-  MahmoudMohamedMahmoudAhmedMohamedElmongui$AddChild("مصطفى")
AserMostafaMahmoudMohamedMahmoudAhmedMohamedElmongui <-  MostafaMahmoudMohamedMahmoudAhmedMohamedElmongui$AddChild("آسر")
AbdelfatahMohamedMahmoudAhmedMohamedElmongui <-  MohamedMahmoudAhmedMohamedElmongui$AddChild("عبدالفتاح")
HatemAbdelfatahMohamedMahmoudAhmedMohamedElmongui <-  AbdelfatahMohamedMahmoudAhmedMohamedElmongui$AddChild("حاتم")
NancyHatemAbdelfatahMohamedMahmoudAhmedMohamedElmongui <-  HatemAbdelfatahMohamedMahmoudAhmedMohamedElmongui$AddChild("نانسي")
MahaAbdelfatahMohamedMahmoudAhmedMohamedElmongui <-  AbdelfatahMohamedMahmoudAhmedMohamedElmongui$AddChild("مها")
ZaynabMahmoudAhmedMohamedElmongui <-  MahmoudAhmedMohamedElmongui$AddChild("زينب")

# ElsayedAhmedMohamedElmongui
AbdelmoneimElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("عبدالمنعم")
AidaAbdelmoneimElsayedAhmedMohamedElmongui <-  AbdelmoneimElsayedAhmedMohamedElmongui$AddChild("عايدة")
AhmedElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("أحمد")
ElsayedAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("محمدالسيد")
SamiraAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("سميرة")
RefaatAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("محمدرفعت")
AhmedRefaatAhmedElsayedAhmedMohamedElmongui <-  RefaatAhmedElsayedAhmedMohamedElmongui$AddChild("أحمد")
ImanRefaatAhmedElsayedAhmedMohamedElmongui <-  RefaatAhmedElsayedAhmedMohamedElmongui$AddChild("إيمان")
MRaafatAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("محمدرأفت")
AidaMRaafatAhmedElsayedAhmedMohamedElmongui <-  MRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("عايدة")
HossamMRaafatAhmedElsayedAhmedMohamedElmongui <-  MRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("حسام")
NagwaHossamMRaafatAhmedElsayedAhmedMohamedElmongui <-  HossamMRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("نجوى")
RaafatHossamMRaafatAhmedElsayedAhmedMohamedElmongui <-  HossamMRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("رأفت")
NermeenMRaafatAhmedElsayedAhmedMohamedElmongui <-  MRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("نرمين")
AhmedMRaafatAhmedElsayedAhmedMohamedElmongui <-  MRaafatAhmedElsayedAhmedMohamedElmongui$AddChild("أحمد")
KadriAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("محمدقدرى")
RamiKadriAhmedElsayedAhmedMohamedElmongui <-  KadriAhmedElsayedAhmedMohamedElmongui$AddChild("رامي")
KarimKadriAhmedElsayedAhmedMohamedElmongui <-  KadriAhmedElsayedAhmedMohamedElmongui$AddChild("كريم")
HamdyAhmedElsayedAhmedMohamedElmongui <-  AhmedElsayedAhmedMohamedElmongui$AddChild("محمدحمدى")
YasminHamdyAhmedElsayedAhmedMohamedElmongui <-  HamdyAhmedElsayedAhmedMohamedElmongui$AddChild("ياسمين")
AhmedHamdyAhmedElsayedAhmedMohamedElmongui <-  HamdyAhmedElsayedAhmedMohamedElmongui$AddChild("أحمد")
ElsayedaElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("السيدة")
MohamedElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("محمد")
HassanElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("حسن")
AhmedHassanElsayedAhmedMohamedElmongui <-  HassanElsayedAhmedMohamedElmongui$AddChild("أحمد")
MamdouhHassanElsayedAhmedMohamedElmongui <-  HassanElsayedAhmedMohamedElmongui$AddChild("محمد ممدوح")
MohamedMamdouhHassanElsayedAhmedMohamedElmongui <-  MamdouhHassanElsayedAhmedMohamedElmongui$AddChild("محمد")
ShaymaaMamdouhHassanElsayedAhmedMohamedElmongui <-  MamdouhHassanElsayedAhmedMohamedElmongui$AddChild("شيماء")
HassanMamdouhHassanElsayedAhmedMohamedElmongui <-  MamdouhHassanElsayedAhmedMohamedElmongui$AddChild("حسن")
ManalHassanElsayedAhmedMohamedElmongui <-  HassanElsayedAhmedMohamedElmongui$AddChild("منال")
SaharHassanElsayedAhmedMohamedElmongui <-  HassanElsayedAhmedMohamedElmongui$AddChild("سحر")
SabreyaElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("صبرية/نجية")
IbrahimElsayedAhmedMohamedElmongui <-  ElsayedAhmedMohamedElmongui$AddChild("ابراهيم")
MostafaIbrahimElsayedAhmedMohamedElmongui <-  IbrahimElsayedAhmedMohamedElmongui$AddChild("مصطفى")
IbrahimMostafaIbrahimElsayedAhmedMohamedElmongui <-  MostafaIbrahimElsayedAhmedMohamedElmongui$AddChild("ابراهيم")
MohamedMostafaIbrahimElsayedAhmedMohamedElmongui <-  MostafaIbrahimElsayedAhmedMohamedElmongui$AddChild("محمد")
AshrafIbrahimElsayedAhmedMohamedElmongui <-  IbrahimElsayedAhmedMohamedElmongui$AddChild("أشرف")
MostafaAshrafIbrahimElsayedAhmedMohamedElmongui <-  AshrafIbrahimElsayedAhmedMohamedElmongui$AddChild("مصطفى")
#DaughterAshrafIbrahimElsayedAhmedMohamedElmongui <-  AshrafIbrahimElsayedAhmedMohamedElmongui$AddChild("أشرف")
AshganIbrahimElsayedAhmedMohamedElmongui <-  IbrahimElsayedAhmedMohamedElmongui$AddChild("أشجان")
HowaydaIbrahimElsayedAhmedMohamedElmongui <-  IbrahimElsayedAhmedMohamedElmongui$AddChild("هويدة")

# MohamedAhmedMohamedElmongui
MohamedMohamedAhmedMohamedElmongui <-  MohamedAhmedMohamedElmongui$AddChild("محمد")
AminMohamedAhmedMohamedElmongui <-  MohamedAhmedMohamedElmongui$AddChild("أمين")

# HassanAhmedMohamedElmongui
AzimaHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("عظيمة")
AtteyatHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("عطيات")
ShokreyaHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("شكرية")
MohamedHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("محمد")
HassanMohamedHassanAhmedMohamedElmongui <-  MohamedHassanAhmedMohamedElmongui$AddChild("حسن")
MohamedHassanMohamedHassanAhmedMohamedElmongui <-  HassanMohamedHassanAhmedMohamedElmongui$AddChild("محمد")
RihamMohamedHassanMohamedHassanAhmedMohamedElmongui <-  MohamedHassanMohamedHassanAhmedMohamedElmongui$AddChild("ريهام")
FaresMohamedHassanMohamedHassanAhmedMohamedElmongui <-  MohamedHassanMohamedHassanAhmedMohamedElmongui$AddChild("فارس")
AhmedMohamedHassanMohamedHassanAhmedMohamedElmongui <-  MohamedHassanMohamedHassanAhmedMohamedElmongui$AddChild("أحمد")
NourhanHassanMohamedHassanAhmedMohamedElmongui <-  HassanMohamedHassanAhmedMohamedElmongui$AddChild("نورهان")
AmaalHassanMohamedHassanAhmedMohamedElmongui <-  HassanMohamedHassanAhmedMohamedElmongui$AddChild("أمال")
FawzeyaMohamedHassanAhmedMohamedElmongui <-  MohamedHassanAhmedMohamedElmongui$AddChild("فوزية")
NadiaMohamedHassanAhmedMohamedElmongui <-  MohamedHassanAhmedMohamedElmongui$AddChild("نادية")
AmaalMohamedHassanAhmedMohamedElmongui <-  MohamedHassanAhmedMohamedElmongui$AddChild("أمال")
AlyHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("على")
OthmanHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("عثمان")
WagihHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("وجيه")
SalahHassanAhmedMohamedElmongui <-  HassanAhmedMohamedElmongui$AddChild("صلاح")



# AlyAhmedMohamedElmongui
MohamedAlyAhmedMohamedElmongui <-  AlyAhmedMohamedElmongui$AddChild("محمد")

###print(AhmedMohamedElmongui)

SetNodeStyle(AhmedMohamedElmongui, shape="box", style="rounded")
#SetNodeStyle(MahmoudAhmedMohamedElmongui, style="filled", fillcolor="GreenYellow")
AhmedMohamedElmongui$Revert()
#plot(AhmedMohamedElmongui)

library(networkD3)
useRtreeList <- ToListExplicit(AhmedMohamedElmongui, unname = TRUE)
radialNetwork(useRtreeList)
```

```{r echo=FALSE, fig.width=20, fig.align="center"}

library(data.tree)

AlyElaissawyElmongui <- Node$new("علي العيسوي المنجي")
ElaissawyAlyElaissawyElmongui <-  AlyElaissawyElmongui$AddChild("العيسوي")
AlyElaissawyAlyElaissawyElmongui <-  ElaissawyAlyElaissawyElmongui$AddChild("علي")
MohamedAlyElaissawyAlyElaissawyElmongui <-  AlyElaissawyAlyElaissawyElmongui$AddChild("محمد")
MohamedMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("محمد")
MohamedMohamedMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("محمد")
OmarMohamedMohamedMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedMohamedMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("عمر")
FaroukMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("فاروق")
AhmedFaroukMohamedAlyElaissawyAlyElaissawyElmongui <-  FaroukMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("أحمد")
FaroukAhmedFaroukMohamedAlyElaissawyAlyElaissawyElmongui <-  AhmedFaroukMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("فاروق")
GamalMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("جمال")
MohamedGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  GamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("محمد")
GamalMohamedGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedGamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("جمال")
YassinMohamedGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedGamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("ياسين")
EhabGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  GamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("ايهاب")
HodaEhabGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  EhabGamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("هدى")
AbdelwahabEhabGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  EhabGamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("عبدالوهاب")
BasmatEhabGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  EhabGamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("بسمات")
HagarGamalMohamedAlyElaissawyAlyElaissawyElmongui <-  GamalMohamedAlyElaissawyAlyElaissawyElmongui$AddChild("هاجر")
CamiliaMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("كامليا")
FadiaMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("فادية")
MagdaMohamedAlyElaissawyAlyElaissawyElmongui <-  MohamedAlyElaissawyAlyElaissawyElmongui$AddChild("ماجدة")


ElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyAlyElaissawyElmongui$AddChild("العيسوي")
AbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyAlyElaissawyElmongui$AddChild("عبدالوهاب")
ElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("المندوة")
RedaElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  ElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("رضا")
MamdouhElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  ElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("ممدوح")
ElsayedElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  ElmandowaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("السيد")
AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("علي")
NagehAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("ناجح")
AbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("عبدالرازق")
AhmedAbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("أحمد")
MahmoudAbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمود")
EmanAbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelrazakAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("إيمان")
AshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("أشرف")
AlyAshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("علي")
MohamedAshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمد")
KarimAshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("كريم")
YasminAshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AshrafAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("ياسمين")
HamdyAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("حمدي")
MahmoudAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمود")
MohamedNagehAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  NagehAlyAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمد")
IbrahimAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("ابراهيم")
MohamedIbrahimAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  IbrahimAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمد")
MohsenIbrahimAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  IbrahimAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محسن")
MArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  AbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمدعرفه")
HanyMArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  MArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("هاني")
HaythamMArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  MArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("هيثم")
SamehMArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui <-  MArafaAbdelwahabElaissawyElaissawyAlyElaissawyElmongui$AddChild("سامح")
AlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyAlyElaissawyElmongui$AddChild("السعيد")
SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("سلامة")
MohamedSalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمد")
AhmedSalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("أحمد")
ShaymaaSalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("شيماء")
AmiraSalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("أميرة")
OlaSalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  SalamaAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("علا")
AbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("عبدالمنعم")
NesmaAbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("نسمه")
NehalAbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("نهال")
NadaAbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AbdelmoneimAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("ندا")
AhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("أحمد")
AhmedAhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("أحمد")
MahmoudAhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمود")
EmanAhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AhmedAlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("إيمان")
HabibaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("حبيبه")
KarimaAlsaeedElaissawyElaissawyAlyElaissawyElmongui <-  AlsaeedElaissawyElaissawyAlyElaissawyElmongui$AddChild("كريمه")
ElaissawyElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyAlyElaissawyElmongui$AddChild("العيسوي")
MahmoudElaissawyElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمود")
IbrahimElaissawyElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyElaissawyAlyElaissawyElmongui$AddChild("ابراهيم")
MohamedElaissawyElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyElaissawyAlyElaissawyElmongui$AddChild("محمد")
ElsayedElaissawyElaissawyAlyElaissawyElmongui <-  ElaissawyElaissawyAlyElaissawyElmongui$AddChild("السيد")
ElsayedElsayedElaissawyElaissawyAlyElaissawyElmongui <-  ElsayedElaissawyElaissawyAlyElaissawyElmongui$AddChild("السيد")
DotsAlyElaissawyElmongui <-  AlyElaissawyElmongui$AddChild("...")
MostafaDotsAlyElaissawyElmongui <-  DotsAlyElaissawyElmongui$AddChild("مصطفى")
MostafaMostafaDotsAlyElaissawyElmongui <-  MostafaDotsAlyElaissawyElmongui$AddChild("مصطفى")
ZakiMostafaMostafaDotsAlyElaissawyElmongui <-  MostafaMostafaDotsAlyElaissawyElmongui$AddChild("زكي")
AwadZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("عوض")
AminAwadZakiMostafaMostafaDotsAlyElaissawyElmongui <-  AwadZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("أمين")
MohamedAwadZakiMostafaMostafaDotsAlyElaissawyElmongui <-  AwadZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("محمد")
ShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("شعبان")
AymanShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("أيمن")
HusseunShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("حسين")
MohamedShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("محمد")
SamehShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ShaabanZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("سامح")
FathallaZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("فتح الله")
NagahFathallaZakiMostafaMostafaDotsAlyElaissawyElmongui <-  FathallaZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("نجاح")
MohamedFathallaZakiMostafaMostafaDotsAlyElaissawyElmongui <-  FathallaZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("محمد")



GamalZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("جمال")
TarekZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("طارق")
HeshamZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("هشام")
MohamedZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("محمد")
ZakiZakiMostafaMostafaDotsAlyElaissawyElmongui <-  ZakiMostafaMostafaDotsAlyElaissawyElmongui$AddChild("زكي")
MostafaMostafaMostafaDotsAlyElaissawyElmongui <-  MostafaMostafaDotsAlyElaissawyElmongui$AddChild("مصطفى")
HamdyMostafaMostafaMostafaDotsAlyElaissawyElmongui <-  MostafaMostafaMostafaDotsAlyElaissawyElmongui$AddChild("حمدي")
AlsaeedMostafaMostafaDotsAlyElaissawyElmongui <-  MostafaMostafaDotsAlyElaissawyElmongui$AddChild("السعيد")
MahmoudAlsaeedMostafaMostafaDotsAlyElaissawyElmongui <-  AlsaeedMostafaMostafaDotsAlyElaissawyElmongui$AddChild("محمود")
AlsayedAlsaeedMostafaMostafaDotsAlyElaissawyElmongui <-  AlsaeedMostafaMostafaDotsAlyElaissawyElmongui$AddChild("السيد")
IbrahimElaissawyAlyElaissawyElmongui <-  ElaissawyAlyElaissawyElmongui$AddChild("ابراهيم")
IbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimElaissawyAlyElaissawyElmongui$AddChild("ابراهيم")
IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("ابراهيم")
IsmailIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("اسماعيل")
MohamedIsmailIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IsmailIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("محمد")
MohamedIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("محمد")
GamalIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("جمال")
FerialIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("فريال")
SanaaIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("سناء")
NabaweyaIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("نبوية")
AmaalIbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("أمال")
AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("عبدالحميد")
AbdelgawadAbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("عبدالجواد")
ShaabanAbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("شعبان")
SalmaAbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("سلمى")
NafisaAbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("نفيسة")
RagaaAbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  AbdelhameedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("رجاء")
ElsayedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  IbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("السيدالعربي")
SamyElsayedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  ElsayedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("سامي ")
MohamedElsayedIbrahimIbrahimElaissawyAlyElaissawyElmongui <-  ElsayedIbrahimIbrahimElaissawyAlyElaissawyElmongui$AddChild("محمد")


AlyElaissawyElmongui$Revert()
SetNodeStyle(AlyElaissawyElmongui, style="rounded", shape = "box")
SetNodeStyle(MostafaDotsAlyElaissawyElmongui, style="filled,rounded", shape = "box", color="lightblue")
SetNodeStyle(MohamedAlyElaissawyAlyElaissawyElmongui, style="filled,rounded", shape = "box", color="lightgreen")
plot(AlyElaissawyElmongui)

library(networkD3)
useRtreeList <- ToListExplicit(AlyElaissawyElmongui, unname = TRUE)
radialNetwork(useRtreeList)
```
